name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
      
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dashboard code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: pnpm
      - name: Install package and build
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build
      - name: Compress files
        run: |
          mv public dashboard
          zip -r dashboard.zip dashboard
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dashboard.zip
          prerelease: false
